name: AshJR → Ashmini (build)
on:
  workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Kick Ashmini build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ASH_TOKEN }}
          repository: juggaloares417/Ashmini
          event-type: build
