name: AshJR → Ashmini (build)
on:
  workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to Ashmini via GitHub API
        env:
          ASH_TOKEN: ${{ secrets.ASH_TOKEN }}
        run: |
          set -euo pipefail
          code=$(
            curl -sS -o /tmp/resp -w "%{http_code}" \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${ASH_TOKEN}" \
              https://api.github.com/repos/juggaloares417/Ashmini/dispatches \
              -d '{"event_type":"build"}'
          )
          echo "HTTP ${code}"
          if [ "$code" != "204" ]; then
            echo "Body:"; cat /tmp/resp; exit 1
          fi
          echo "Dispatch sent ✔"
